[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build>=0.16.7",
    "torch==2.0.0",
    "torchvision==0.15.1",
    "ninja; platform_system!='Windows'"
]

build-backend = "setuptools.build_meta"
